#!/usr/bin/env ruby
# encoding: utf-8
require 'tmrb'

Dir.chdir(File.expand_path('../..', __FILE__)) do
  tmux = TmRb::Multiplexer.new
  # creates an empty window
  tmux.new_session(session_name: 'command_exec')

  tmux.new_window(name: 'code',     command: "zsh -c 'vim -p -c \\\":NERDTree lib/\\\"'")
  tmux.new_window(name: 'spec',     command: "zsh -c 'vim -p -c \\\":NERDTree spec\\\"'")
  tmux.new_window(name: 'features', command: "zsh -c 'vim -p -c \\\":NERDTree features\\\"'")
  tmux.start
end
